### ISSUE TITLE
Some improvement suggestions

### ISSUE THREAD

**Issue by zhefox** [harlamism/IdaClu#4]
It seems that the search and sorting functions are missing and cannot be sorted based on commits.
At the same time, it would be better if there is a filtering function, which is the search function mentioned above.

**Comment by harlamism** [comment]
The **sorting feature** is now available. When at least one clustering node in the tree view is expanded, sorting is determined by function properties _(Name, Folder, Address, Size, Chunks, Nodes, Edges, Comment)_. If all nodes are collapsed, sorting is based on node names. The **filtering feature** is work in progress.

**Comment by harlamism** [comment]
Finally, the **search/filter feature** is there. Press the _Ctrl+F_ key combination when the main tree/table view is active to toggle filters. The corresponding input fields will appear below the column headers.
