### ISSUE TITLE
Please add caching.

### ISSUE THREAD

**Issue by DoctorGoat** [harlamism/IdaClu#5]
If the binary hasn't changed since the last read, it would be nice if IdaClu would cache results and not need to parse the file again.

**Comment by harlamism** [comment]
Hi! A prototype **feature for result caching** has just been aired. Currently, it caches the basic cluster structure, and then augments this skeleton with additional function  metadata. This means it will continue to work even if function labels _(prefixes/folders/colors)_ are changed after saving. Over time, this feature may become more advanced. Consider the button with the diskette icon at the bottom right of the plugin.
