### ISSUE TITLE
Can you add a button to abort current operation?

### ISSUE THREAD

**Issue by karpiyon** [harlamism/IdaClu#6]
Thanks for this great plugin!
Is it possible to add a button to abort current operation?
I may run it on large binaries and need to quit current operation if it takes too long.

**Comment by DoctorGoat** [comment]
I run it on large binaries and I wish it was multithreaded or didn't take up all of IDA to run. Some of these options are useful, and I'm afraid to touch them half the time.

**Comment by harlamism** [comment]
> Is it possible to add a button to abort current operation?

Hi! I'm also glad to hear you found it useful. The feature has been added - please try the latest version from the repository.
Additionally, I think a time estimate could be quite handy, so I’ve added it to the task list.

**Comment by harlamism** [comment]
> I run it on large binaries and I wish it was multithreaded or didn't take up all of IDA to run.

This topic is somewhat different, so if there are no objections, I will create a new issue based on your comment.

> As of IDA 7.2, all APIs not explicitly marked THREAD_SAFE have to be called from the main thread in IDA. If they aren't, IDA throws a RuntimeError: Function can be called from the main thread only. 
> https://pypi.org/project/jfx-bridge-ida/

It appears that things have changed since the release of IDA Pro v9.0/idalib.
